# run in cmd line :
# 'conda env create -f environment.yml'
# 'conda activate twitter-sentiment'

name: twitter-sentiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tweepy
  - matplotlib
  - matplotlib-inline
  - seaborn
  - numpy
  - pandas
  - scikit-learn
  - statsmodels
  - nltk
  - pip:
      - datasets
