# run in cmd line 'conda env create -f environment.yml'

name: twitter-sentiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tweepy
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - pip:
      - tensorflow==2.10
      - tensorflow-datasets